### ISSUE TITLE
Slab.ini file created in unexpected location

### ISSUE THREAD

**Issue by megagrump** [flamendless/Slab#110]
Running the Slab demo from `/home/me/projects/Slab` with `love .` will create `/home/me/projects/Slab.ini` (one directory up). I haven't tested what happens on other platforms.

I suppose the intent is to create the file next to the `.love` or `.exe` file? This can fail in many cases; the user might not have write access to that location. For example, if you distribute your game as a Linux package for some distro, it will be installed in a location where there is no write access for non-root users.

The game's designated save directory would be the right location for the file imo.

**Comment by flamendless** [comment]
Oh yeah I forgot about this one. It happens to me as well on Linux.

> The game's designated save directory would be the right location for the file imo.

Yeah this sounds good.

**Comment by flamendless** [comment]
I think my commit for this is sufficient

**Comment by flamendless** [comment]
I have updated the API and made more examples in the snippet in the wiki
