### ISSUE TITLE
Documentation and behavior for some elements unclear?

### ISSUE THREAD

**Issue by frissyn** [flamendless/Slab#130]
In the Slab documentation for [`Slab.BeginWindow(...)`](https://github.com/flamendless/Slab/wiki/Window#BeginWindow) a number of options are listed, but the side effects of each option being enabled/disabled are a bit unclear. Nothing is a major overlook, but I did have to spend of bit of time playing around with the options to come to right conclusions.

+ If `AutoSizeContent` is set to `false`, the window will no longer display scrollbars if the content overflows.
+ If a `MainMenuBar` exists in the viewport, setting the `X` and `Y` of a Window to `0` will account for the height of the bar. (Ideal behavior, but that isn't documented, so I assumed otherwise.)

There are some other weird caveats as well.

+ In [`Slab.Text(...)`](https://github.com/flamendless/Slab/wiki/Text#Text), the `Pad` option appears to apply the pixel padding to *both* sides of the text. (I could be wrong, but in all my usage of that option it seemed to be that way)
+ In [`Slab.SameLine(...)`](https://github.com/flamendless/Slab/wiki/Cursor#SameLine), the `Pad` option applies the pixel padding to only the *right* side of the last element of the previous line. Expected behavior, but conflicts with how the Pad option works for `Slab.Text`

Just a general heads up, I'll update this issue if I find more. 👍🏽

**Comment by flamendless** [comment]
Thank you :) I'll update the wiki according to your findings
