### ISSUE TITLE
Add a Label override to Slab.Button's Options table.

### ISSUE THREAD

**Issue by MatthewBlanchard** [flamendless/Slab#131]
The item id of a button is tied to a it's label. Sometimes I want multiple buttons with the same label, but that causes issues with hover events. Label override would let you use the first string argument to button as an ID.

**Comment by flamendless** [comment]
Will add this API for the `v1.0.0` release:
```lua
Slab.Button("id", {Label = "MyButton"})
```
if no `opt.Label` is passed, the `id` and the `label` will be the first argument "id"

**Comment by flamendless** [comment]
Hi, this has been committed now to the `v1.0.0` branch
