### ISSUE TITLE
Windows Are Unaware of the Menu Bar

### ISSUE THREAD

**Issue by dcuny** [flamendless/Slab#133]
Windows can be dragged up so the window's titlebar is behind the menubar.

If you release the window during a drag and it's behind the menubar, there's no obvious way to put it back into position.

**Comment by flamendless** [comment]
Thanks for reporting this. This will be fixed and released along v1.0.0

**Comment by flamendless** [comment]
Hi @dcuny , this is fixed now in the `master` branch as well
