### ISSUE TITLE
[v1.0.0] - Listbox error

### ISSUE THREAD

**Issue by chicogamedev** [flamendless/Slab#135]
I have this piece of code : 

```
for k, v in ipairs(self.projectsList) do
    Slab.BeginListBoxItem("projectItem" .. k, { Selected = self.selectedProjectIndex == k } )
	   Slab.Text(v.name)

	    if (Slab.IsListBoxItemClicked()) then
	        self.selectedProjectIndex = k
	    end

            if (Slab.IsListBoxItemClicked(1, true)) then
	         self:loadProject(k)
	    end
    Slab.EndListBoxItem()
end
```

I got this error (not with current released version of Slab) : 

Error: libs/slab/Internal/UI/ListBox.lua:151: Begin was called for item 'nil' without a call to EndListBoxItem
stack traceback:
	[love "boot.lua"]:345: in function <[love "boot.lua"]:341>
	[C]: in function 'error'
	libs/slab/Internal/UI/ListBox.lua:151: in function 'BeginItem'
	libs/slab/API.lua:1633: in function 'BeginListBoxItem'

It seems that active.ActiveItem is nil for whatever reason.

**Comment by flamendless** [comment]
You should be using `BeginListBox` and `EndListBox` before calling `BeginListBoxItem`

**Comment by chicogamedev** [comment]
Yeah sorry since the error was not here with the older version of Slab, these calls are around the given code. Sorry for not showing them. 

```
			Slab.BeginListBox("projectsList", { Clear = self.projectsListUpdate, StretchW = false, StretchH = true, W = 440, AlignX = "Center" })
				self.projectsListUpdate = false
				for k, v in ipairs(self.projectsList) do
					Slab.BeginListBoxItem("projectItem" .. k, { Selected = self.selectedProjectIndex == k } )
						Slab.Text(v.name)

						if (Slab.IsListBoxItemClicked()) then
							self.selectedProjectIndex = k
						end

						if (Slab.IsListBoxItemClicked(1, true)) then
							self:loadProject(k)
						end
					Slab.EndListBoxItem()
				end
			Slab.EndListBox()
```

**Comment by flamendless** [comment]
Indeed, there is an error in latest commit. Will fix soon

**Comment by chicogamedev** [comment]
Thanks !

**Comment by flamendless** [comment]
Fixed now :)
