### ISSUE TITLE
[v1.0.0] - All buttons text are completely off

### ISSUE THREAD

**Issue by chicogamedev** [flamendless/Slab#136]
Does not happens with the **master** version of Slab : 

<img width="1392" alt="Capture d’écran 2022-07-25 à 18 28 12" src="https://user-images.githubusercontent.com/6854475/180828539-f76d4881-a1e2-48e8-9b36-a5430f8e4e11.png">

**Comment by chicogamedev** [comment]
Actually my whole interface is completely broken : 
<img width="1392" alt="v1 0 0" src="https://user-images.githubusercontent.com/6854475/180829093-73ad666d-100e-4ead-9ec2-b8cfb8988c3a.png">


Master version : 

<img width="1392" alt="Master" src="https://user-images.githubusercontent.com/6854475/180829148-deed10aa-eab3-45f5-9df5-6e29d6c4eafc.png">

**Comment by chicogamedev** [comment]
Important to note that the open file dialog is completely broken too. Maybe the usage have changed between **Master** and **v1.0.0** ?

**Comment by flamendless** [comment]
Please show reproducible code we can use to replicate this one

**Comment by flamendless** [comment]
Should be fixed now.

**Comment by chicogamedev** [comment]
It is ! Thanks
