### ISSUE TITLE
[v1.0.0] - Slab.IsVoidHovered() not returning true correctly

### ISSUE THREAD

**Issue by chicogamedev** [flamendless/Slab#139]
It's for sure not working the same way as on the **master** branch. Is that wanted ?

**Comment by flamendless** [comment]
Please provide a minimal reproducible code we can use to test and verify the fix :)

**Comment by flamendless** [comment]
Should be fixed now

**Comment by chicogamedev** [comment]
Thanks for your correction, sorry for no context and code I was on the rush and it asked a bit of preparation to provide a usable context. 

Thanks for great work. Hope this v1.0.0 will be the best possible 👊🏼🤘🏼

**Comment by flamendless** [comment]
Thank you for raising issues as well, it helped me narrow down, find, and fix bugs that sometimes are common to other bugs as well. _Looking at you `Region.IsScrolling()`_
