### ISSUE TITLE
iOS supported?

### ISSUE THREAD

**Issue by mvolkmann** [flamendless/Slab#151]
When I run the demo app I get the following error:

/Internal/Input/Mouse.lua:170: Cannot create system cursor: CreateSystemCursor is not currently supported

Is this expected when running in iOS?

**Comment by flamendless** [comment]
I'll check it as soon as possible though i won't be able to test since I don't have any ios device

**Comment by flamendless** [comment]
@mvolkmann Hi, `CreateSystemCursor ` is not part of Slab but is part of the love framework. 

I have added a handling to not use cursor-related feature for iOS instead [see commit](https://github.com/flamendless/Slab/commit/a762b382345d6935146f2fd61da26e1fecea930a)

Though I can't test this, let me know in this thread if there's more error related to mouse/cursor.
