### ISSUE TITLE
Option to Always Show Scrollbar

### ISSUE THREAD

**Issue by MikuAuahDark** [flamendless/Slab#166]
Currently to make Slab show scrollbar, the `AutoSizeWindow` needs to be set to false. However in my use case, this is not possible since I need the window to be resizable. The screen size may also change. Furthermore, I can't determine exactly how much elements I'll put into.

**Comment by flamendless** [comment]
@MikuAuahDark  you can now achieve this using the `ShowScrollbarX` or `ShowScrollbarY`

Example:
```lua
	Slab.BeginWindow("MyFirstWindow", {
		Title = "My First Window",
		ShowScrollbarX = true,
		ShowScrollbarY = true,
	})
		Slab.Text("Hello World")
	Slab.EndWindow()
```

**Comment by MikuAuahDark** [comment]
Cool, I'll test it out ASAP.
