### ISSUE TITLE
Slab obstructs user drawings when windows are minimized or docked

### ISSUE THREAD

**Issue by wingnut-2019** [flamendless/Slab#173]
Minimizing a Slab window obstructs non-Slab related drawings until another Slab window becomes focused or you maximize the window again.

Refer to the main.lua file (https://gist.github.com/wingnut-2019/8bdd86e2d50cd97af8edcc42a83d4df2) and perform these steps to reproduce:
run the file
minimize "My First Window" -> the image png1 drawn in love.draw becomes invisible
left-click on "My Second Window" -> image png1 becomes visible again

Docking windows (manually by user or with the Slab API) seems to cause the problem as well.
I did run the provided example main.lua file with the Slab version prior to when docking windows was introduced and the problem does not occur with that Slab version.

**Comment by flamendless** [comment]
Thank you! Will check this as soon as I have the time

**Comment by flamendless** [comment]
Sorry bout the delay, working on it now

**Comment by flamendless** [comment]
@wingnut-2019  you can fix it by setting the color (`love.graphics.setColor(1, 1, 1, 1)`) back before drawing the images. Nevertheless I pushed a commit for this.
