### ISSUE TITLE
Is it possible to make a transparent window Slab or to make a picture instead of the usual background?

### ISSUE THREAD

**Issue by BestHatzker** [flamendless/Slab#5]

**Comment by coding-jackalope** [comment]
Hi BestHatzker,

Changing the background color of a window is as simple as passing the a transparent color into the BgColor option in the BeginWindow function.

```lua
local BgColor = Slab.GetStyle().WindowBackgroundColor
Slab.BeginWindow('Color', {Title = "Color", BgColor = {BgColor[1], BgColor[2], BgColor[3], 0.35}})
Slab.Text("Hello World")
Slab.EndWindow()
```

The above code will retrieve the default color for window backgrounds and apply the same color with a different alpha to make the window background transparent. Remember that Lua tables are passed by reference so making a change to BgColor will affect all windows, so it's best to copy the table. Hope this helps.

**Comment by flamendless** [comment]
@BestHatzker  can confirm that the snippet:
```lua
local BgColor = Slab.GetStyle().WindowBackgroundColor
Slab.BeginWindow('Color', {Title = "Color", BgColor = {BgColor[1], BgColor[2], BgColor[3], 0.35}})
Slab.Text("Hello World")
Slab.EndWindow()
```
works.
