### ISSUE TITLE
BlueScreen on SlabTest.lua

### ISSUE THREAD

**Issue by PericlesDagod** [flamendless/Slab#86]
![image](https://user-images.githubusercontent.com/39133947/113808143-ac1ced00-9765-11eb-8bb2-beaa2b90c411.png)

When dragging those min max inputs
![image](https://user-images.githubusercontent.com/39133947/113808203-cf479c80-9765-11eb-9e9e-920a7b81402c.png)

**Comment by flamendless** [comment]
@PericlesDagod  this has been fixed in the v0.8.0 release. Please let me know if problem still persists.
