### ISSUE TITLE
[Enhancment] Mouse wheel scroll horizontially when no vertical scroll bar

### ISSUE THREAD

**Issue by Dude112113** [flamendless/Slab#87]
Title says it all, when there is no vertical scroll bar, but there is a horizontal one, scroll horizontally with the mouse wheel
It would be nice to be able to control the scrolling behaviour as well.

**Comment by flamendless** [comment]
Hi @Dude112113 , will get to this as soon as I can. I still need to figure out how scrolling in a view works internally in Slab

**Comment by flamendless** [comment]
@Dude112113  this is implemented now. Horizontal scrolling will be the default if there is no possible vertical scrolling. Scrolling behavior is not yet implemented as I am still pondering what configuration is needed for the scrolling behavior.
